namespace = "CanisterPK"
output-directory = "./Candid"

[[clients]]
name = "CanisterLogin"
type = "canister"
canister-id = "woimf-oyaaa-aaaan-qegia-cai"

[[clients]]
name = "CanisterMatchMaking"
type = "canister"
canister-id = "vqzll-jiaaa-aaaan-qegba-cai"

[[clients]]
name = "CanisterStats"
type = "canister"
canister-id = "jybso-3iaaa-aaaan-qeima-cai"

[[clients]]
name = "testnft"
type = "canister"
canister-id = "phgme-naaaa-aaaap-abwda-cai"

[[clients]]
name = "testicrc1"
type = "canister"
canister-id = "svcoe-6iaaa-aaaam-ab4rq-cai"

[[clients]]
name = "validator"
type = "canister"
canister-id = "2dzox-tqaaa-aaaan-qlphq-cai"

[[clients]]
name = "chests"
type = "canister"
canister-id = "w4fdk-fiaaa-aaaap-qccgq-cai"

[[clients]]
name = "flux"
type = "canister"
canister-id = "plahz-wyaaa-aaaam-accta-cai"

[[clients]]
name = "BoomToken"
type = "canister"
canister-id = "vtrom-gqaaa-aaaaq-aabia-cai"

[[clients]]
name = "Rewards"
type = "canister"
canister-id = "bm5s5-qqaaa-aaaap-qcgfq-cai"

[[clients]]
name = "database"
type = "canister"
canister-id = "erbra-lyaaa-aaaap-qhmfa-cai"

[[clients]]
name = "tournaments"
type = "canister"
canister-id = "lqaq5-paaaa-aaaap-qhndq-cai"